on:
  push:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish on jme library
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        
      - name: Push
        uses: jMonkeyEngine/jme-library-publish-action@1.0
        with:
          data: "./entry.json"
          fetch-repo: nil
          userId: ${{ secrets.LIBRARY_USER_ID }}
          authId: ${{ secrets.LIBRARY_KEY_ID }}
          authKey: ${{ secrets.LIBRARY_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
