on:
  push:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish on jme library
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        
      - name: Push
        if: github.event_name == 'release'
        uses: riccardobl/jme-library-action@v0.1
        with:
          data: "./entry.json"
          userId: ${{ secrets.LIBRARY_USER_ID }}
          authId: ${{ secrets.LIBRARY_KEY_ID }}
          authKey: ${{ secrets.LIBRARY_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
